### ISSUE TITLE
different  between qt5.12.9 qt5.14.2

### ISSUE THREAD

**Issue by sajadblog** [KDAB/kuesa#143]
hi 
tnx for kuesa project that help perfectly work at 3d application
there is a undetermined issue in kuesa application that compiled by qt5.12.9 and qt5.14.2
a simple blender project export to gltf and show at simple application
when i compile application with qt5.12.9 material and object color is like solid mode render at blender and
when i compile application with qt5.14.2 material and object color is like full mode render at blender just like uploaded picture 
the test application and gltf is same at two application

![test](https://user-images.githubusercontent.com/10378510/87541634-c9c99400-c6b6-11ea-8069-fc9c77b94fac.png)

and i want a fully render mode(that show at 5.14.2) view at a application that compiled by  5.12.9

**Comment by lemirep** [comment]
Hello,
Have you tried with Qt 5.15? Could you attach a sample glTF file so that we can investigate please?
Thanks

**Comment by sajadblog** [comment]
my project must compile by qt 5.12.9 but i can test them at qt5.15 and send you the result.

-blender version 2.83
-kuesa dev branch 
-and exported by official gltf exporter at blender 


[testKuesa.tar.gz](https://github.com/KDAB/kuesa/files/4925563/testKuesa.tar.gz)
blender project and gltf file ==> https://gofile.io/d/4NJZ5z

* testKuesa.tar.gz ==> test application that show different view at 5.12.9 and 5.14.2
* orginal.blend ==> the blender project that designer send to us
* fromOrginal.gltf ==> gltf file that exported from orginal.blend and has different view at qt version
* gltfImported.blend ==> blender project that fromOrginal.gltf file imported into them and in solid view we see a view right look like testKuesa application compiled by qt 5.12.9 and on full render mode see view like qt 5.14.2 compilation of testKuesa test application.
Thanks

**Comment by lemirep** [comment]
![image](https://user-images.githubusercontent.com/4984723/87674856-e0cfbb00-c776-11ea-88c5-f85afcbbce41.png)
That's what I'm getting with Kuesa and Qt 5.15
![image](https://user-images.githubusercontent.com/4984723/87675179-4e7be700-c777-11ea-8e34-d44e55217d19.png
Here's what Blender gives me with the original .blend you provided (I don't know how you obtained the full render view, I used the eevee viewport).
Both Blender and Kuesa look consistent from what I can see here but I understand that's not the output you are expecting.

One thing I have observed is that the Blender Material uses a custom node graph. As far as I'm aware the gltf exporter, only handles the Principled BSDF if you want PBR based material or Emissive if you want an unlit single color material. The mix shaders on the output however aren't supported so I'm surprised the exported gltf looks so close to blender.

**Comment by sajadblog** [comment]
after compile some version of kuesa and qt finally i found problem .
in dev-branch of kuesa is this problem and when i compile kuesa v1.2 by qt 5.12.9 get right view like what you share.
thank you a lot. (y)

**Comment by sajadblog** [comment]
just a question.is there any reason to force us to use 3dMax or another gltf exporter application,reason like fully support material or any limitation that now exist in blender exporter ? 
are you accept other application against blender to export and load gltf into kuesa ?

**Comment by mkrus** [comment]
Kuesa will normally fully support Blender and any well behaved gltf 2.0 exporter.
