### ISSUE TITLE
Error when executing one the examples 

### ISSUE THREAD

**Issue by ssooffiiaannee** [KDAB/kuesa#144]
I downloaded the kuesa git repository, I run 
qmake 
make 
make install, 
everything went fine, I opened this directory using Qt Creator, and tried to execute one of the examples, then I get these errors: 
```
Qt3D.Renderer.OpenGL.Backend: Unable to find suitable Texture Unit
Qt3D.Renderer.OpenGL.Backend: FBO incomplete 
```
When I checked my OpenGL version, I get: `OpenGL version string: 3.1 Mesa 18.2.8`
Maybe the problem comes from the OpenGL version because 3.2 version or above is required, but I don't know how to upgrade it, I tried for several hours to change the version but I couldn't.
![image](https://user-images.githubusercontent.com/37119086/88255853-d8690a00-ccb9-11ea-9eb2-e888d2a9e3b4.png)

![image](https://user-images.githubusercontent.com/37119086/88255824-c5563a00-ccb9-11ea-8887-8826536c0441.png)

**Comment by lemirep** [comment]
Hello,
What kind of hardware are you running on? If your hardware does support OpenGL 3.2, then it should just be a matter of updating your mesa driver or installing the AMD/NVidia proprietary driver if your GPU is from one of these makers.

**Comment by ssooffiiaannee** [comment]
My GPU is an Intel(R) UHD Graphics 620, I'm running Qt on a virtual machine, could you show me the command lines to upgrade OpenGL, I'm not sure I'm using the proper command for the upgrade, I tried sudo apt-get install freeglut3-dev, but it's still version 3.1

**Comment by lemirep** [comment]
I'm not sure using a VM will work for that, I'd suggest trying to get this build on the native os as VM and drivers is unlikely to work as efficiently. Also, you VM might be using Mesa to emulate OpenGL and that's why it might not support GL 3.2 properly. I have unfortunately no idea what the proper commands are to get mesa up to date on your OS/device.

**Comment by ssooffiiaannee** [comment]
I suppose it is possible to run it in windows, I use nmake to run the makefile, and I get this 👍 
![image](https://user-images.githubusercontent.com/37119086/89539358-f1b2a000-d7fb-11ea-8fd7-1d08c4e1cad5.png)

**Comment by lemirep** [comment]
Could you try to open the project inside Qt Creator and build it from there?
To perform the `make install` step from there, you will need to go to Project -> Build -> Add Build Step and add Make arguments add install
Alternatively maybe one of the comments on https://stackoverflow.com/questions/33126119/building-qt-nmake-fatal-error-u1077-cd-return-code-0x2 fixes your issue. Make sure install path is not too long and doesn't contain spaces.

**Comment by ssooffiiaannee** [comment]
When I build I get this : 
![image](https://user-images.githubusercontent.com/37119086/89550486-f3836000-d809-11ea-83c2-7decefc482e8.png)

it seems like I'm missing a critical step, here are all the steps I did : download kuesa directory, opened kuesa using qt creator, run qmake on kuesa project, then build.

**Comment by mkrus** [comment]
ignore qml errors, and the warnings. Any actual build errors?

**Comment by ssooffiiaannee** [comment]
I never use qt in windows, when I installed it I thought it's qt creator 5.15, but it's qt creator 4.12 community edition, I have a wierd feeling about this.

This is what I get when I run qmake.

![image](https://user-images.githubusercontent.com/37119086/89555936-f46bc000-d810-11ea-9c98-9cda72f55fb8.png)

this is what I get when I build : 

![image](https://user-images.githubusercontent.com/37119086/89556578-e5d1d880-d811-11ea-8ff9-329fac8f4c28.png)

**Comment by mkrus** [comment]
Looks like you didn't follow the [build instructions](https://github.com/KDAB/kuesa#installation). In particular you need to install perl (make sure it's in the path), and if you've used a tar file (rather that a git clone), create an empty .git folder

**Comment by ssooffiiaannee** [comment]
The pearl is installed and added in the path, I use windows 10 by the way : 

![image](https://user-images.githubusercontent.com/37119086/89562548-68f72c80-d81a-11ea-8004-5e7f7e4a21c1.png)

I've added the .git folder :

![image](https://user-images.githubusercontent.com/37119086/89563092-34d03b80-d81b-11ea-82dc-b8e23cbe5ba0.png)

**Comment by ssooffiiaannee** [comment]
I reinstalled everything on ubuntu 20.04 LTS, I ran the car-scene example : 

![image](https://user-images.githubusercontent.com/37119086/89646202-9e078b80-d8bb-11ea-885f-a093e62a80cf.png)

along with these errors : 

![image](https://user-images.githubusercontent.com/37119086/89645994-38b39a80-d8bb-11ea-8701-9a268b238131.png)

I get these when I ran the musicbox example: 

![image](https://user-images.githubusercontent.com/37119086/89646551-474e8180-d8bc-11ea-9d6d-c1b5bf07fb8f.png)

**Comment by lemirep** [comment]
Ah right, it seems you didn't get the lfs assets.
Easiest would be 1) install git-lfs following instructions on https://git-lfs.github.com/ 2) clone kuesa again 3) check that textures in kuesa/examples/kuesa/assets/envmaps/pink_sunrise have a valid size (should be around 15MB per texture I believe)
Then you should be able to rebuild and hopefully see something

**Comment by ssooffiiaannee** [comment]
Finally, thank you, it works, I get some error messages, but It works . 
Now is it enough to just add Qt += kuesa in Qt creator to work with these APIs?
 Is there C++ APIs of kuesa? is it possible to reproduce these examples using c++?

**Comment by mkrus** [comment]
check the many ducks example, that is in C++
